# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import wangblog.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='username')),
                ('userkey', models.CharField(max_length=128, null=True, unique=True, verbose_name='user key')),
                ('name', models.CharField(blank=True, db_column=b'first_name', max_length=200, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_managed', models.BooleanField(default=False, help_text='Designates whether this user should be treated as managed. Select this to disallow the user from modifying their account (username, password, etc).', verbose_name='managed')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2016, 4, 16, 10, 35, 17, 464089), verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', wangblog.models.user.UserManager()),
            ],
        ),
    ]
