# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 10, 37, 20, 346485), verbose_name='date joined'),
        ),
    ]
