# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangblog', '0002_auto_20160416_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 10, 38, 21, 680394), verbose_name='date joined'),
        ),
    ]
