# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangblog', '0003_auto_20160416_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_domain',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 10, 39, 53, 312133), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=123456, max_length=11, null=True, unique=True),
        ),
    ]
