# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangblog', '0007_auto_20160417_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
